### ISSUE TITLE
Add new onboarding strategy

### ISSUE THREAD

**Issue by damyan** [ironcore-dev/FeDHCP#192]
# Summary
Currently, the `metal` plugin onboards (i.e. creates `Endpoint`s) only for known inventories from a static list. See https://github.com/ironcore-dev/FeDHCP?tab=readme-ov-file#configuration-5. 

## Basic example
Enhance the inventory configuration to a more comprehensive format. Example:
```yaml
namePrefix: server-
hosts:
  - name: machine-1
    macAddress: aa:bb:cc:dd:ee:ff
  - name: machine-2
    macAddress: 11:22:33:44:55:66
macPrefixFilter:
  - aa:aa:aa:aa:aa:aa
  - bb:bb:bb:bb:bb:bb
```
Onboarding algorithm:
- if a static `hosts` section exists, onboard only those inventories (matches current behaviour)
- if no static `hosts` section exists, onboard the inventories with MAC addresses matching the `macFilter`, according to the following naming scheme:
  - if a `namePrefix` section exists, each inventory shall get a suffix-generated name like `server-abcd`, `server-uxyz`, etc.
  - if no `namePrefix` section exists, generate the name with the predefined prefix `compute`, resulting in names like `compute-abcd`,  `compute-uxyz`, etc.
 - if neither `hosts` nor `macFilter` section is  specified, do *not* onboard anything. We want a restrictive onboarding approach, though, that might change in the future
## Motivation
We want more flexibility:
- we don't (always) want pets as servers, we might as well go on and onboard every available inventory
- we want more flexibility about the naming scheme
- we want to support filtering, a.k.a. onboard inventories matching certain criteria
